### ISSUE TITLE
TS typings failed to resolve

### ISSUE THREAD

**Issue by margo-yunanova** [mrdannael/react-coolicons#3]
Pls find below the error which appears after import module in TypeScript (typescript@5.4.3):

Could not find a declaration file for module 'react-coolicons'. 'node_modules/react-coolicons/dist/esm/index.js' implicitly has an 'any' type.
There are types at 'node_modules/react-coolicons/dist/types/index.d.ts', but this result could not be resolved when respecting package.json "exports". The 'react-coolicons' library may need to update its package.json or typings.ts(7016)

**Comment by mrdannael** [comment]
Thanks for the issue. I will look at it :smiley:

**Comment by mrdannael** [comment]
Hi @margo-yunanova . Just released v2.0.1. This issue should be fixed now :wink:
