### ISSUE TITLE
it is necessary to add support for className props

### ISSUE THREAD

**Issue by lidforce** [mrdannael/react-coolicons#4]
If it is present, it is worth adding information about it to the README.

**Comment by mrdannael** [comment]
Hi! Have you tried applying `className` to the icon component?

I mentioned in the Readme.md that "Icons accept common SVG properties." `class` is one of those properties, but in React, `className` is the valid property for the `class` attribute.

[SVG properties from MDN docs](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute)

If the README isn't clear enough, I'm happy to extend it or add a link to the MDN documentation to help out :wink:

**Comment by lidforce** [comment]
Yo, I'm using TailwindCSS, and className doesn't work in any way in NextJS for icon components. 
I think there is a problem specifically when using Tailwind, as I have not been able to resize a component using `w-x`, `h-x` or `size-x`. The icon remained the same size in all cases.

**Comment by mrdannael** [comment]
Ok, i'll look into it then. Thanks for the usage example.

**Comment by mrdannael** [comment]
Looks like the issue it that viewBox is not present within generated icon components. 
Workin' on it!

**Comment by mrdannael** [comment]
@lidforce I've released v3.0.0 to the NPM registry. Let me know if this issue is fixed :smile:

**Comment by lidforce** [comment]
@mrdannael Yes, it works, the sizes change. But now the standard size of icons is very much reduced, I think it is worth to put the standard size at `24px` and if a different one is specified, overwrite the standard one with the specified one.
or, alternatively, correctly handle incoming parameters such as width, color, height and other classes that visually change the icon.
![image](https://github.com/mrdannael/react-coolicons/assets/54450326/79b877e0-dba4-4dce-bc3b-ee3fc853513c)
![image](https://github.com/mrdannael/react-coolicons/assets/54450326/9ac7e464-3a7b-4e16-9de9-0a621b7b5a96)

Another idea is to somehow bind a config, where you can specify svg icons, and which can be called, but I think it is unlikely to apply to this project. :)

Anyway, I'm very glad I found your project. I hope in the foreseeable future the number of icons will increase many times, even if they are not from the coolicons pack

**Comment by mrdannael** [comment]
The standard `24px` size seems right to me. Well, to be honest I was researching how other icon packages were handling the size attribute and some of them had `24px` as a default and some `1em` 😅 I agree that the standard size might be too small. I'll release minor version tommorow 😃 

Thank you for your kind words! I'm thrilled to hear that you find the package valuable.

**Comment by mrdannael** [comment]
@lidforce `3.1.0` released with default size set to 24px.

Thx for being part of the journey!

**Comment by lidforce** [comment]
> @lidforce `3.1.0` released with default size set to 24px.
> 
> Thx for being part of the journey!

Oh, yeah, thank You. <3
